#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# Ensure the commit message contains an issue number

if [[ -z "$(head -n1 "$1" | grep -o -E '#[0-9]+')" ]]; then
  echo >&2 ERROR: Commit message must include issue number.
  exit 1
fi
