#define PLUS                            1
#define MINUS                           2
#define DIVIDE                          3
#define TIMES                           4
#define EXPONENT                        5
#define SEMICOLON                       6
#define INCLUDE                         7
#define STRING                          8
#define RBRACE                          9
#define IDENTIFIER                     10
#define LBRACE                         11
#define COMMA                          12
#define EQUAL                          13
#define LBRACKET                       14
#define RBRACKET                       15
#define PATHIDENTIFIER                 16
#define INTEGER                        17
#define FLOAT                          18
#define INT_DECL                       19
#define FLOAT_DECL                     20
#define STRING_DECL                    21
