#define PLUS                            1
#define MINUS                           2
#define DIVIDE                          3
#define TIMES                           4
#define EXPONENT                        5
#define SEMICOLON                       6
#define INCLUDE                         7
#define STRING                          8
#define RBRACE                          9
#define IDENTIFIER                     10
#define LBRACE                         11
#define COMMA                          12
#define EQUAL                          13
#define LBRACKET                       14
#define RBRACKET                       15
#define INTEGER                        16
#define FLOAT                          17
#define INT_DECL                       18
#define FLOAT_DECL                     19
#define STRING_DECL                    20
